apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: cassandra
  namespace: zmon
spec:
  serviceName: cassandra
  replicas: 5
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: cassandra-data
    spec:
      securityContext:
        fsGroup: 111
      containers:
      - name: cassandra
        image: registry.opensource.zalan.do/stups/scylladb:1.3.2-rc6
        ports:
        - containerPort: 9042
          name: cql
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: intra-node-ssl
        - containerPort: 7199
          name: jmx
        env:
        - name: SCYLLA_MEMORY
          value: "6G"
        - name: SCYLLA_SMP
          value: "4"
        - name: SCYLLA_SEEDS
          value: cassandra-0.cassandra.zmon.svc.cluster.local,cassandra-1.cassandra.zmon.svc.cluster.local
        - name: LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        volumeMounts:
        - name: cassandra-data96
          mountPath: /var/lib/scylla
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data96
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 250Gi
